name: Build Zed

on:
  push:
    branches:
      - main
      - "v[0-9]+.[0-9]+.x"
    tags:
      - "v*"
  pull_request:
    branches:
      - "**"
  workflow_dispatch:

concurrency:
  # Allow only one workflow per any non-`main` branch.
  group: ${{ github.workflow }}-${{ github.ref_name }}-${{ github.ref_name == 'main' && github.sha || 'anysha' }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  CARGO_INCREMENTAL: 0
  RUST_BACKTRACE: 1

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          clean: false
          submodules: "recursive"

      - name: Cache dependencies
        uses: swatinem/rust-cache@v2
        with:
          save-if: ${{ github.ref == 'refs/heads/main' }}

      - name: Update Rust
        run: |
            rustup update
            rustup target add wasm32-wasi

      - name: Build Zed
        run: cargo build --release

      - name: Test Zed
        run: cargo test --workspace

      - name: Upload Windows Build Artifact
        uses: actions/upload-artifact@v3.1.0
        with:
          # Artifact name
          name: target
          # A file, directory or wildcard pattern that describes what to upload
          path: target
          if-no-files-found: warn
          # Duration after which artifact will expire in days. 0 means using default retention.
          retention-days: 1
